# Generated by Django 4.2.1 on 2023-06-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_tag_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
